# Generated by Django 5.1.2 on 2024-12-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("message", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="order_id",
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name="message",
            name="shop_id",
            field=models.IntegerField(default=-1),
        ),
    ]
