# Generated by Django 5.1.2 on 2024-11-11 09:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shoppingcart",
            old_name="create_date",
            new_name="updated_date",
        ),
    ]
