# Generated by Django 5.1.2 on 2024-11-11 03:21

from django.db import migrations


def create_initial_categories(apps, schema_editor):
    Category = apps.get_model('shop', 'Category')
    db_alias = schema_editor.connection.alias

    INITIAL_CATEGORIES = [
        '电子产品',
        '服装',
        '家居用品',
        '书籍',
        '食品',
        '玩具',
        '运动用品',
        '美容护肤',
        '汽车用品',
        '办公用品',
    ]

    for category_name in INITIAL_CATEGORIES:
        Category.objects.using(db_alias).get_or_create(name=category_name)


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0006_category_product_category"),
    ]

    operations = [
        migrations.RunPython(create_initial_categories),
    ]
