# Generated by Django 5.1.2 on 2024-11-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0007_auto_20241111_1121"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="total_income",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
