# Generated by Django 5.1.2 on 2024-11-20 02:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0010_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sales_volume",
            field=models.IntegerField(default=0),
        ),
    ]
