# Generated by Django 5.1.2 on 2024-12-02 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0014_alter_sellershop_seller"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sellershop",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shop_sellers",
                to="shop.shop",
            ),
        ),
    ]
