# Generated by Django 5.1.2 on 2024-12-06 02:26

from django.db import migrations


def create_initial_categories(apps, schema_editor):
    Category = apps.get_model('shop', 'Category')
    db_alias = schema_editor.connection.alias

    INITIAL_CATEGORIES = [
        '其它'
    ]

    for category_name in INITIAL_CATEGORIES:
        Category.objects.using(db_alias).get_or_create(name=category_name)


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0016_alter_review_unique_together"),
    ]

    operations = [
        migrations.RunPython(create_initial_categories)
    ]
