# Generated by Django 5.1.2 on 2024-12-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0018_alter_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoptransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("Income", "Income"),
                    ("Refund", "Refund"),
                    ("Divide", "Divide"),
                ],
                max_length=10,
            ),
        ),
    ]
