# Generated by Django 5.1.2 on 2024-11-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="money",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
