# Generated by Django 5.1.2 on 2024-12-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_user_money"),
        ("shop", "0014_alter_sellershop_seller"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="shops",
            field=models.ManyToManyField(
                related_name="sellers", through="shop.SellerShop", to="shop.shop"
            ),
        ),
    ]
