# Generated by Django 5.1.2 on 2024-11-19 03:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0003_order_total_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending Payment", "待支付"),
                    ("Payment Received", "已支付待收货"),
                    ("Shipped", "已发货"),
                    ("Completed", "已完成"),
                    ("Cancelled", "已取消"),
                ],
                default="Pending Payment",
                max_length=50,
            ),
        ),
    ]
